<?php

/**
 * @file
 * Preprocess includes.
 */

include_once __DIR__ . '/preprocess/block.inc';
include_once __DIR__ . '/preprocess/breadcrumb.inc';
include_once __DIR__ . '/preprocess/html.inc';
include_once __DIR__ . '/preprocess/menu.inc';
include_once __DIR__ . '/preprocess/node.inc';
include_once __DIR__ . '/preprocess/paragraph.inc';
include_once __DIR__ . '/preprocess/region.inc';
include_once __DIR__ . '/preprocess/views_view.inc';
include_once __DIR__ . '/preprocess/views_view_fields.inc';
