_core:
  default_config_hash: R4IF-ClDHXxblLcG0L7MgsLvfBIMAvi_skumNFQwkDc
module:
  address: 0
  admin_toolbar: 0
  admin_toolbar_tools: 0
  better_exposed_filters: 0
  block: 0
  block_content: 0
  breakpoint: 0
  captcha: 0
  cas: 0
  ckeditor: 0
  comment: 0
  config: 0
  config_filter: 0
  config_ignore: 0
  config_pages: 0
  config_split: 0
  content_moderation: 0
  contextual: 0
  crop: 0
  cshs: 0
  ctools: 0
  datetime: 0
  dblog: 0
  devel: 0
  diff: 0
  dynamic_page_cache: 0
  editor: 0
  entity_reference_revisions: 0
  extra_field: 0
  feeds: 0
  feeds_dependency: 0
  feeds_ex: 0
  feeds_tamper: 0
  field: 0
  field_ui: 0
  file: 0
  file_delete: 0
  file_mdm: 0
  file_mdm_exif: 0
  file_mdm_font: 0
  filter: 0
  fixed_block_content: 0
  focal_point: 0
  geolocation: 0
  google_tag: 0
  hal: 0
  image: 0
  image_effects: 0
  imagemagick: 0
  inline_form_errors: 0
  jquery_ui: 0
  jquery_ui_datepicker: 0
  jquery_ui_slider: 0
  jquery_ui_touch_punch: 0
  language: 0
  link: 0
  link_attributes: 0
  linkit: 0
  media: 0
  media_file_delete: 0
  media_library: 0
  menu_breadcrumb: 0
  menu_link_content: 0
  menu_ui: 0
  metatag: 0
  metatag_open_graph: 0
  metatag_twitter_cards: 0
  migrate: 0
  migrate_conditions: 0
  migrate_devel: 0
  migrate_drupal: 0
  migrate_plus: 0
  migrate_source_csv: 0
  migrate_tools: 0
  migration_tools: 0
  mysql: 0
  node: 0
  options: 0
  page_cache: 0
  pantheon_advanced_page_cache: 0
  paragraphs_table: 0
  path: 0
  path_alias: 0
  path_redirect_import: 0
  rabbit_hole: 0
  recaptcha: 0
  redirect: 0
  responsive_favicons: 0
  responsive_image: 0
  rest: 0
  rh_node: 0
  rh_taxonomy: 0
  scheduler: 0
  search_api: 0
  search_api_db: 0
  search_api_pantheon: 0
  search_api_pantheon_admin: 0
  search_api_solr: 0
  seckit: 0
  serialization: 0
  shortcut: 0
  simple_sitemap: 0
  smart_trim: 0
  social_media_links: 0
  sophron: 0
  stage_file_proxy: 0
  syslog: 0
  system: 0
  tamper: 0
  taxonomy: 0
  telephone: 0
  text: 0
  token: 0
  token_filter: 0
  toolbar: 0
  twig_tweak: 0
  ultimate_cron: 0
  update: 0
  user: 0
  views_ajax_history: 0
  views_infinite_scroll: 0
  views_ui: 0
  viewsreference: 0
  webform: 0
  webform_ui: 0
  workbench_access: 0
  workflows: 0
  extlink: 1
  pathauto: 1
  cshs_menu_link: 5
  externalauth: 10
  views: 10
  paragraphs: 11
  standard: 1000
theme:
  olivero: 0
  claro: 0
profile: standard
