_core:
  default_config_hash: l58O_yEXSo-SeJi19LXdzTU1tNJG3lmnIhCitRkM1tk
langcode: en
uuid: 07bb792c-2f88-46f3-b3f1-036823c3e966
name: 'University of San Francisco'
mail: website-donotreply@usfca.edu
slogan: ''
page:
  403: ''
  404: /node/11779
  front: /node/1034
admin_compact_mode: false
weight_select_max: 100
default_langcode: en
mail_notification: ''
