features:
  node_user_picture: false
  comment_user_picture: true
  comment_user_verification: true
  favicon: 1
logo:
  use_default: 1
favicon:
  use_default: 1
description:
  value: "<p>2130 Fulton Street<br />\r\nSan Francisco, CA 94117-1080<br />\r\n<a href=\"tel:+415-422-5555\">415-422-5555</a></p>\r\n"
  format: full_html
copyright:
  value: "<p>Copyright © [current-date:html_year] University of San Francisco</p>\r\n"
  format: basic_html
